config/routes.rb
Rails.application.routes.draw do
  resources :pastries

  get 'beans/' => 'beans#index'

  get 'beans/new' => 'beans#new'

  get 'beans/:id' => 'beans#show', as: :bean

  post 'beans/' => 'beans#create'

  get 'beans/:id/edit' => 'beans#edit'

  patch 'beans/:id' => 'beans#update'

  delete 'beans/:id' => 'beans#destroy'

end

app/models/bean.rb
class Bean
  include Mongoid::Document
  field :name, type: String
  field :roast, type: String
  field :origin, type: String
  field :quantity, type: Float
end

app/models/pastry.rb
class Pastry
  include Mongoid::Document
  field :name, type: String
  field :type, type: String
  field :price, type: Float
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beans_controller.rb
class BeansController < ApplicationController

	def index
		@beans = Bean.all
	end

	def show
		@bean = Bean.find(params[:id])
	end

	def new
		@bean = Bean.new
	end

	def create 
		@bean = Bean.new(params.require(:bean).permit(:name, :roast, :origin, :quantity))
		if @bean.save
			redirect_to beans_path
		else
			render 'new'
		end
	end

	def edit
		@bean = Bean.find(params[:id])
	end

	def update
		@bean = Bean.find(params[:id])
		if @bean.update_attributes(params.require(:bean).permit(:name, :roast, :origin, :quantity))
			redirect_to beans_path
		else
			render 'edit'
		end
	end

	def destroy
		@bean = Bean.find(params[:id])
		@bean.destroy
		redirect_to beans_path
	end
end

app/controllers/pastries_controller.rb
class PastriesController < ApplicationController
  before_action :set_pastry, only: [:show, :edit, :update, :destroy]

  # GET /pastries
  # GET /pastries.json
  def index
    @pastries = Pastry.all
  end

  # GET /pastries/1
  # GET /pastries/1.json
  def show
  end

  # GET /pastries/new
  def new
    @pastry = Pastry.new
  end

  # GET /pastries/1/edit
  def edit
  end

  # POST /pastries
  # POST /pastries.json
  def create
    @pastry = Pastry.new(pastry_params)

    respond_to do |format|
      if @pastry.save
        format.html { redirect_to @pastry, notice: 'Pastry was successfully created.' }
        format.json { render :show, status: :created, location: @pastry }
      else
        format.html { render :new }
        format.json { render json: @pastry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pastries/1
  # PATCH/PUT /pastries/1.json
  def update
    respond_to do |format|
      if @pastry.update(pastry_params)
        format.html { redirect_to @pastry, notice: 'Pastry was successfully updated.' }
        format.json { render :show, status: :ok, location: @pastry }
      else
        format.html { render :edit }
        format.json { render json: @pastry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pastries/1
  # DELETE /pastries/1.json
  def destroy
    @pastry.destroy
    respond_to do |format|
      format.html { redirect_to pastries_url, notice: 'Pastry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pastry
      @pastry = Pastry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pastry_params
      params.require(:pastry).permit(:name, :type, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beans_helper.rb
module BeansHelper
end

app/helpers/pastries_helper.rb
module PastriesHelper
end

app/views/beans/edit.html.erb
<h1> Edit this coffee! </h1>

<%= form_for @bean do |f| %>
	Name: <%= f.text_field :name, placeholder: "Name" %>
	<%= f.text_field :roast, placeholder: "Roast"%>
	<%= f.text_field :origin, placeholder: "Origin" %>
	<%= f.number_field :quantity, placeholder: "Quantity" %>

	<%= f.submit "Edit beans!" %>

<% end %>

<%= link_to "Back to the list!", beans_path %>

app/views/beans/index.html.erb
   <h1>Today's Beans</h1>
    <ul>
        <% @beans.each do |b| %>
            <li>
                <strong> <%= b.name %> </strong> -- <%= b.roast %> <%= link_to "Show more details!", bean_path(b) %>
            </li>
        <% end %>
    </ul>

app/views/beans/new.html.erb
<h1> Add a new coffee! </h1>

<%= form_for @bean do |f| %>
	Name: <%= f.text_field :name, placeholder: "Name" %>
	<%= f.text_field :roast, placeholder: "Roast"%>
	<%= f.text_field :origin, placeholder: "Origin" %>
	<%= f.number_field :quantity, placeholder: "Quantity" %>

	<%= f.submit "Add beans!" %>

<% end %>

<%= link_to "Back to the list!", beans_path %>

app/views/beans/show.html.erb
<h1><%= @bean.name %></h1>

<p>This coffee is a <%= @bean.roast %> roast from <%= @bean.origin %>, and we have <%= @bean.quantity %> pounds available. </p>

<%= link_to "Delete this bean!", :bean, method: :delete, data: { confirm: "Are you sure you want to delete #{@bean.name}?"} %>

<%= link_to "Back to the list!", beans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railscafe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pastries/_form.html.erb
<%= form_for(@pastry) do |f| %>
  <% if @pastry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pastry.errors.count, "error") %> prohibited this pastry from being saved:</h2>

      <ul>
      <% @pastry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pastries/edit.html.erb
<h1>Editing pastry</h1>

<%= render 'form' %>

<%= link_to 'Show', @pastry %> |
<%= link_to 'Back', pastries_path %>

app/views/pastries/index.html.erb
<h1>Listing pastries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pastries.each do |pastry| %>
      <tr>
        <td><%= pastry.name %></td>
        <td><%= pastry.type %></td>
        <td><%= pastry.price %></td>
        <td><%= link_to 'Show', pastry %></td>
        <td><%= link_to 'Edit', edit_pastry_path(pastry) %></td>
        <td><%= link_to 'Destroy', pastry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pastry', new_pastry_path %>

app/views/pastries/new.html.erb
<h1>New pastry</h1>

<%= render 'form' %>

<%= link_to 'Back', pastries_path %>

app/views/pastries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pastry.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @pastry.type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pastry.price %>
</p>

<%= link_to 'Edit', edit_pastry_path(@pastry) %> |
<%= link_to 'Back', pastries_path %>